pks_api_hostname: api.pks.sandbox.azure.technopoly.io
pivotal-container-service_persistent_disk_size: "102400"
pivotal-container-service_elb_names: sandbox-pks-lb

cloud_provider/azure/default_security_group: sandbox-bosh-deployed-vms-security-group
cloud_provider/azure/location: centralus
cloud_provider/azure/resource_group_name: sandbox
cloud_provider/azure/vnet_name: sandbox-virtual-network
cloud_provider/azure/vnet_resource_group_name: sandbox

# ldap
uaa/ldap/email_domains:
uaa/ldap/external_groups_whitelist:
uaa/ldap/first_name_attribute:
uaa/ldap/group_search_base:
uaa/ldap/group_search_filter:
uaa/ldap/last_name_attribute:
uaa/ldap/ldap_referrals: follow
uaa/ldap/mail_attribute_name:
uaa/ldap/search_base:
uaa/ldap/search_filter:
uaa/ldap/server_ssl_cert:
uaa/ldap/server_ssl_cert_alias:
uaa/ldap/url:
