az2_name:
az3_name:
cloud_provider/azure/azure_cloud_name:
cloud_provider/azure/azure_master_managed_identity:
cloud_provider/azure/azure_worker_managed_identity:
cloud_provider/azure/default_security_group:
cloud_provider/azure/location:
cloud_provider/azure/primary_availability_set:
cloud_provider/azure/resource_group_name:
cloud_provider/azure/subscription_id:
cloud_provider/azure/tenant_id:
cloud_provider/azure/vnet_name:
cloud_provider/azure/vnet_resource_group_name:
network_name:
pivotal-container-service/pks_tls/certificate:
pivotal-container-service/pks_tls/privatekey:
pks_api_hostname:
plan1_selector/active/errand_vm_type:
plan1_selector/active/master_az_placement:
plan1_selector/active/master_persistent_disk_type:
plan1_selector/active/master_vm_type:
plan1_selector/active/worker_az_placement:
plan1_selector/active/worker_persistent_disk_type:
plan1_selector/active/worker_vm_type:
plan2_selector/active/description:
plan2_selector/active/errand_vm_type:
plan2_selector/active/master_az_placement:
plan2_selector/active/master_instances:
plan2_selector/active/master_persistent_disk_type:
plan2_selector/active/master_vm_type:
plan2_selector/active/max_worker_instances:
plan2_selector/active/name:
plan2_selector/active/worker_az_placement:
plan2_selector/active/worker_instances:
plan2_selector/active/worker_persistent_disk_type:
plan2_selector/active/worker_vm_type:
plan3_selector/active/description:
plan3_selector/active/errand_vm_type:
plan3_selector/active/master_az_placement:
plan3_selector/active/master_instances:
plan3_selector/active/master_persistent_disk_type:
plan3_selector/active/master_vm_type:
plan3_selector/active/max_worker_instances:
plan3_selector/active/name:
plan3_selector/active/worker_az_placement:
plan3_selector/active/worker_instances:
plan3_selector/active/worker_persistent_disk_type:
plan3_selector/active/worker_vm_type:
service_network_name:
singleton_availability_zone:
uaa/ldap/credentials_identity:
uaa/ldap/credentials_password:
uaa/ldap/email_domains:
uaa/ldap/external_groups_whitelist:
uaa/ldap/first_name_attribute:
uaa/ldap/group_search_base:
uaa/ldap/group_search_filter:
uaa/ldap/last_name_attribute:
uaa/ldap/ldap_referrals:
uaa/ldap/mail_attribute_name:
uaa/ldap/search_base:
uaa/ldap/search_filter:
uaa/ldap/server_ssl_cert:
uaa/ldap/server_ssl_cert_alias:
uaa/ldap/url:
