version: '3.7'

services:
  uaa:
    container_name: uaa
    image: pcfseceng/uaa
    volumes: ["./config/uaa.yml:/uaa/uaa.yml"]
    ports: ["8080:8080"]
    restart: always

  credhub:
    container_name: credhub
    image: orangeopensource/credhub
    # image: pcfseceng/credhub
    ports: ["9000:9000"]
    depends_on: ["uaa"]
    environment:
      UAA_URL: http://localhost:8080/uaa
      UAA_INTERNAL_URL: http://uaa:8080/uaa

  concourse-db:
    container_name: concourse-db
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    container_name: concourse
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db,credhub]
    ports: ["8081:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8081
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CREDHUB_URL: https://credhub:9000
      CONCOURSE_CREDHUB_INSECURE_SKIP_VERIFY: "true"
      CONCOURSE_CREDHUB_CLIENT_ID: credhub_client
      CONCOURSE_CREDHUB_CLIENT_SECRET: secret
