---
azure-subscription-id: ((azure-subscription-id))
azure-tenant-id: ((azure-tenant-id))
azure-client-id: ((azure-client-id))
azure-client-secret: ((azure-client-secret))
azure-ssh-private-key: |
  ((azure-ssh-private-key))
azure-ssh-public-key: ((azure-ssh-public-key))
bosh-storage-account-name: ((bosh-storage-account-name))
