---
azure-subscription-id: ((azure-subscription-id))
azure-resource-group: ((azure-resource-group))
azure-tenant-id: ((azure-tenant-id))
azure-client-id: ((azure-client-id))
azure-client-secret: ((azure-client-secret))
azure-storage-account: ((azure-storage-account))
opsman-ssh-public-key: ((opsman-ssh-public-key))
