pivotal-container-service/pks_tls/certificate: ((cert_pem))
pivotal-container-service/pks_tls/privatekey: ((private_key_pem))
cloud_provider/azure/subscription_id: ((subscription_id))
cloud_provider/azure/tenant_id: ((tenant_id))
uaa/ldap/credentials_identity: ((ldap_bind_dn))
uaa/ldap/credentials_password: ((ldap_bind_password))
